apiVersion: openebs.io/v1alpha1
kind: UpgradeTask
metadata:
  name: upgrade-jiva-volume-@vol_name@
  namespace: openebs
  labels:
    resource: jivaVolume
spec:
  fromVersion: 1.2.0
  imagePrefix: "openebs/"
  imageTag: "ci"
  jivaVolume:
    pvName: @vol_name@
  toVersion: 1.3.0-RC2
status:
  completedTime: null
  retries: 0
  startTime: null
