apiVersion: openebs.io/v1alpha1
kind: UpgradeTask
metadata:
  name: upgrade-cstor-spc-@spc_name@
  namespace: openebs
  labels:
    resource: @label@
spec:
  fromVersion: @from@
  imagePrefix: ""
  imageTag: ""
  storagePoolClaim:
    spcName: @spc_name@
  toVersion: @to@
status:
  completedTime: null
  retries: 0
  startTime: null
