apiVersion: openebs.io/v1alpha1
kind: UpgradeTask
metadata:
  name: upgrade-cstor-spc-@spc_name@
  namespace: openebs
  labels:
    resource: cstorSPC
spec:
  fromVersion: 1.2.0
  imagePrefix: "openebs/"
  imageTag: "ci"
  storagePoolClaim:
    spcName: @spc_name@
  toVersion: 1.3.0-RC2
status:
  completedTime: null
  retries: 0
  startTime: null
