apiVersion: openebs.io/v1alpha1
kind: UpgradeTask
metadata:
  name: upgrade-cstor-volume-@vol_name@
  namespace: openebs
  labels:
    resource: @label@
spec:
  fromVersion: @from@
  imagePrefix: ""
  imageTag: ""
  cstorVolume:
    pvName: @vol_name@
  toVersion: @to@
status:
  completedTime: null
  retries: 0
  startTime: null
